### ISSUE TITLE
Showing the wrong number of rows in a table

### ISSUE THREAD

**Issue by eddiepaz** [SQLPlayer/DataScriptWriter#12]
When I connect to the database, the tables are read and details are displayed. I have a table, "EmployeeType," that I'm certain has 6 records, but the application shows as 12. It does the same with other tables as well. I closed the application and tried again. Same result.

![1-app](https://user-images.githubusercontent.com/175540/88505301-f8375100-cf8b-11ea-8fd9-6754ca9dbee7.png)

![2-ssms](https://user-images.githubusercontent.com/175540/88505309-fb324180-cf8b-11ea-993f-be605d62ebd1.png)

**Comment by NowinskiK** [comment]
Thanks, I will verify the issue.
