### ISSUE TITLE
Can you remove the usage of DevExpress ?

### ISSUE THREAD

**Issue by ssinfod** [SQLPlayer/DataScriptWriter#5]
Is it possible to remove the usage of DevExpress in the project ?
I don't have a DevExpress licence so it does not compile on my computer.

Otherwise, is it possible to compile it without installing DevExpress or can you add the DLL in the project ?

Thanks.

**Comment by NowinskiK** [comment]
Sorry, I'm not planning to do so. DevExpress helps to work with the list of tables (filtering, grouping, etc). Even if I would add DevExpress libraries (dll) you couldn't build it without a valid licence. 
**Alternative 1:** You can fork the code and change it for yourself.
**Alternative 2:** Go to [Releases](https://github.com/SQLPlayer/DataScriptWriter/releases) and you can download compiled version (exe) of this app.
